#!/usr/bin/env bash


function cfmt {
  if [[ $# -lt 1 ]]; then
    echo "Usage: cfmt <file>"
  else
    astyle \
		--style=kr \
		--indent=spaces=4\
		--lineend=linux \
		--attach-inlines \
		--convert-tabs \
		--preserve-date \
		--add-braces \
		--pad-header \
		--indent-switches \
		--align-pointer=name \
		--align-reference=name \
		--pad-oper \
		--pad-comma \
		--suffix=none \
		--break-one-line-headers \
		--add-one-line-braces \
		--add-braces \
		--attach-return-type \
		--max-code-length=80 \
		--indent-preproc-block \
		--min-conditional-indent=2 \
		--break-after-logical \
      $1
  fi
}

if [ -f $1 ]
then
	cfmt $1
else
	if [ -d $1 ]
	then
		for file in `ls $1/*.c $1/*.h 2>/dev/null`
		do
			cfmt $file
		done
	else
		echo "File or firectory not found: $1" > /dev/stderr
	fi
fi
