#!/bin/bash


if [[ $# == 1 ]]; then
    git clone git@git.epitech.eu:/alexis.potelle@epitech.eu/$1

elif [[ $# == 2 ]]; then
    git clone git@git.epitech.eu:/$1@epitech.eu/$2

else
    echo "Usage --> Personel : clone Name_dir"
    echo "Usage --> Etranger : clone Persone Nom_dossier"
fi


